blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.TrendingPostsView, name='home'),
    path('authors/', views.TrendingAuthorsView, name='home_authors'),
    path('write/', views.NewPostView, name='new_post'),
    path('create/', views.CreatePostView, name='create_post'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/edit', views.EditPostView, name='edit_post'),
    path('<slug:slug>/publish', views.PublishPostView, name='publish_post'),
    path('<slug:slug>/unpublish', views.UnpublishPostView, name='unpublish_post'),
    path('<slug:slug>/unlist', views.UnlistPostView, name='unlist_post'),
    path('<slug:slug>/delete', views.DeletePostView, name='delete_post'),
    path('<slug:slug>/report', views.ReportPostView, name='report_post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from mysite.sitemap import PostSitemap, UserSitemap, StaticSitemap
from search.urls import urlpatterns as search_index_urls

sitemaps = {
    'static': StaticSitemap,
    'users': UserSitemap,
    'posts': PostSitemap,
}

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
                  path('auth/logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('recover/',
                       auth_views.PasswordResetView.as_view(
                           html_email_template_name='email_templates/password_reset_email'
                                                    '.html'), name='password_reset'),
                  path('recover/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('tinymce/', include('tinymce.urls')),
                  re_path(r'^search/', include(search_index_urls)),
                  path('', include('users.urls')),
                  path('', include('blog.urls')),
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

blog/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.core import mail
from django.core.mail import get_connection, EmailMultiAlternatives
from django.db import models
from django.db.models.signals import post_save, post_delete, pre_delete
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string
from django.utils.html import strip_tags
from django.utils.text import slugify
from hitcount.models import HitCount
from tinymce.models import HTMLField
from django.core.exceptions import ValidationError

STATUS = (
    (0, "Draft"),
    (1, "Published"),
    (2, "Unlisted"),
)

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now=True)
    excerpt = models.TextField(max_length=200, blank=False, null=False)
    content = HTMLField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    taglist = models.TextField(max_length=200, blank=True, null=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')
    hourly_views = models.IntegerField(editable=False, default=0)
    last_views_snapshot = models.IntegerField(editable=False, default=0)
    featured_image = models.TextField(blank=True, null=True, default='')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    @property
    def views(self):
        return sum([hit_count_generic.hits for hit_count_generic in self.hit_count_generic.all()])

    @property
    def tags(self):
        return [tag.strip() for tag in self.taglist.split(',')] if self.taglist else []

    @property
    def reading_time(self):
        return max([1, int(len(self.raw_content.split(' ')) / 275)])

    @property
    def raw_content(self):
        """content for indexing.
        Used in Elasticsearch indexing.
        """
        return " ".join(strip_tags(str(self.content)).split())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.title))
        super().save(*args, **kwargs)


def get_avatar_path(instance, filename):
    return 'avatars/{0}.png'.format(instance.user.username)


def get_banner_path(instance, filename):
    return 'banners/{0}.png'.format(instance.user.username)


def validate_file_size(value):
    filesize = value.size

    if filesize > 10485760:
        raise ValidationError("The maximum image size is 10MB.")
    else:
        return value


class Profile(models.Model):  # add this class and the following fields
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(max_length=250, null=True, blank=True)
    avatar = models.ImageField(upload_to=get_avatar_path, default='avatars/default.png',
                               validators=[validate_file_size])
    banner = models.ImageField(upload_to=get_banner_path, default='banners/default.png',
                               validators=[validate_file_size])
    github = models.TextField(max_length=39, null=True, blank=True)
    linkedin = models.TextField(max_length=40, null=True, blank=True)
    website = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.user)


REASON = (
    (0, "Other"),
    (1, "Hateful or Harassment"),
    (2, "Sexual or Inappropriate"),
    (3, "Spam or Misleading")
)


class Report(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reported_users',
                             null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reported_posts', null=True, blank=True)
    reporter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reported_by',
                                 null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    reason = models.IntegerField(choices=REASON, default=0)
    comment = models.TextField(max_length=250, null=True, blank=True)
    closing_comment = models.TextField(null=True, blank=True)
    send_follow_up = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        send_follow_up = self.send_follow_up
        send_initial_email = not self.pk
        self.send_follow_up = False
        super().save(*args, **kwargs)

        # follow up closing_comment
        if self.closing_comment and send_follow_up and self.reporter.email:
            context = {
                'username': self.reporter,
                'p1': "We wanted to follow-up with you regarding " + ('a post' if self.post else 'a user') +
                      " report you submitted on " + str(self.created_on.date()) +
                      (", with the following comment \"" + str(self.comment) + "\" " if self.comment else "."),
                'p2': self.closing_comment,
            }
            subject = 'Follow-up on your report'
            html_message = render_to_string('email_templates/static_email_template.html', {'context': context})
            plain_message = strip_tags(html_message)
            from_email = 'Easy Blog <' + settings.DEFAULT_FROM_EMAIL + '>'
            to = self.reporter.email
            mail.send_mail(subject, plain_message, from_email, [to], html_message=html_message)

        # initial email
        if send_initial_email and self.reporter.email:
            print('Report created email sent')
            context = {
                'username': self.reporter,
                'p1': "We want to thank you for reporting " + ('a post' if self.post else 'a user') +
                      " on our platform. ",
                'p2': "After we have reviewed your report, you might receive a follow-up.",
            }
            subject = 'Your report has been received'
            html_message = render_to_string('email_templates/static_email_template.html', {'context': context})
            plain_message = strip_tags(html_message)
            from_email = 'Easy Blog <' + settings.DEFAULT_FROM_EMAIL + '>'
            to = self.reporter.email
            mail.send_mail(subject, plain_message, from_email, [to], html_message=html_message)

    def __str__(self):
        return str(self.pk)


@receiver(post_delete, sender=Post)
def follow_up_post_reports(sender, instance, **kwargs):
    reports = Report.objects.filter(post=instance)
    reporters = set()
    if reports:
        for r in reports:
            if r.reporter.email:
                reporters.add(r.reporter)

        if reporters:
            messages = []
            for reporter in reporters:
                context = {"username": reporter.username,
                           "p1": 'The post you reported has been removed. Some info about post can be found below',
                           "lines": ['Title: ' + instance.title,
                                     'Excerpt: ' + instance.excerpt],
                           "p2": 'Thank you for your report.'
                           }
                messages.append(('Follow-up on your report',
                                 'Hi ' + reporter.username + '\n\nThe post you reported has been removed.\n\n Title: ' + instance.title + '\n Excerpt: ' + instance.excerpt + ' \n\nThank you for your report. \n\nSincerely, \nEasy Blog by Ahmadz.ai ',
                                 render_to_string('email_templates/static_email_template.html', {'context': context}),
                                 'Easy Blog <' + settings.DEFAULT_FROM_EMAIL + '>',
                                 [reporter.email]))

            send_mass_html_mail(messages, fail_silently=False)


@receiver(pre_delete, sender=settings.AUTH_USER_MODEL)
def follow_up_user_reports(sender, instance, **kwargs):
    print(instance.username)
    print(Report.objects.all())
    reports = Report.objects.filter(user__username=instance.username)
    print(reports)
    reporters = set()
    if reports:
        for r in reports:
            if r.reporter.email:
                reporters.add(r.reporter)

        if reporters:
            messages = []
            for reporter in reporters:
                context = {"username": reporter.username,
                           "p1": 'The user you reported has been removed. Some info can be found below',
                           "lines": ['Username: ' + instance.username],
                           "p2": 'Thank you for your report.'
                           }
                messages.append(('Follow-up on your report',
                                 'Hi ' + reporter.username + '\n\nThe user you reported has been removed.\n\n Username: ' + instance.username + ' \n\nThank you for your report. \n\nSincerely, \nEasy Blog by Ahmadz.ai ',
                                 render_to_string('email_templates/static_email_template.html', {'context': context}),
                                 'Easy Blog <' + settings.DEFAULT_FROM_EMAIL + '>',
                                 [reporter.email]))

            send_mass_html_mail(messages, fail_silently=False)


def send_mass_html_mail(datatuple, fail_silently=False, user=None, password=None,
                        connection=None):
    """
    Given a datatuple of (subject, text_content, html_content, from_email,
    recipient_list), sends each message to each recipient list. Returns the
    number of emails sent.

    If from_email is None, the DEFAULT_FROM_EMAIL setting is used.
    If auth_user and auth_password are set, they're used to log in.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea

from blog.models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].disabled = True


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'banner', 'bio', 'github', 'linkedin', 'website')
        widgets = {
            'avatar': forms.FileInput(attrs={'aria-label': 'Avatar'}),
            'banner': forms.FileInput(attrs={'aria-label': 'Banner'}),
            'bio': Textarea(attrs={'aria-label': 'bio', 'cols': 20, 'rows': 6, 'oninput': "auto_grow(this)",
                                   'onkeypress': 'preventLineBreak(event)', 'placeholder': 'Bio'}),
            'github': forms.TextInput(attrs={'aria-label': 'Github URL', 'placeholder': 'username'}),
            'linkedin': forms.TextInput(attrs={'aria-label': 'LinkedIn URL', 'placeholder': 'username'}),
            'website': forms.TextInput(attrs={'aria-label': 'Website URL', 'placeholder': 'www.yourwebsite.com'})
        }


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')


class EmailVerificationForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email',)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="robots" content="index, follow">
    <meta name="revisit-after" content="1 day">
    <meta name="language" content="English">
    <meta name="copyright" content="Hayaturehman Ahmadzai ( Rehman )">
    <meta name="rating" content="general">
    <meta name="distribution" content="global">
    <meta name="theme-color" content="#000000">
    <meta property="og:type" content="website">

    {% block meta %}
        <meta name="title" content="Easy Blog">
        <meta name="description" content="Share your thoughts with ease, freedom and simplicity">
        <meta name="keywords" content="blog, blogging, share, thoughts, world, freedom, simplicity, easy, rehman, hayaturehman, ahmadzai">

        <!-- HTML Meta Tags -->
        <title>Easy Blog</title>
        <meta name="description" content="Easy Blog - Share your thoughts with ease, freedom and simplicity.">

        <!-- Google / Search Engine Tags -->
        <meta itemprop="name" content="Easy Blog">
        <meta itemprop="description" content="Easy Blog - Share your thoughts with ease, freedom and simplicity.">
        <meta itemprop="image" content="http://i.imgur.com/RImMfPo.png">

        <!-- Facebook Meta Tags -->
        <meta property="og:title" content="Easy Blog">
        <meta property="og:description" content="Easy Blog - Share your thoughts with ease, freedom and simplicity.">
        <meta property="og:image" content="http://i.imgur.com/RImMfPo.png">

        <!-- Twitter Meta Tags -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:title" content="Easy Blog">
        <meta name="twitter:description" content="Easy Blog - Share your thoughts with ease, freedom and simplicity.">
        <meta name="twitter:image" content="http://i.imgur.com/RImMfPo.png">

        <meta name="keywords"
              content="blog, blogging, share, thoughts, world, freedom, simplicity, easy, rehman, hayaturehman, ahmadzai">

    {% endblock %}

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/themes.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/messages.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/prism.css' %}">


    {% block styles %}
    {% endblock %}

    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/default.min.css">
</head>
<body class="dark">
<script src="{% static 'js/theme.js' %}"></script>
<script>applyTheme(document.body)</script>
<nav>
    <div id="navbar">
        <div id="leftnav">
            <a href="{% url 'home' %}">Easy Blog</a>
        </div>
        <form action="{% url 'postdocument-list' %}" id="search_bar">
                <input type="text" aria-label="search" name="search" placeholder="Search">
        </form>
        <div style="display: flex; align-items: center;">
            <a href="{% url 'new_post' %}">Write</a>
            <a href="javascript:void(0);" id="dropdown_btn" onclick="toggle('navlinksContainer', 'flex')">
                {% if user.is_authenticated %}
                    <img class="avatar_icon" src="{{aws_media_url}}{{user.profile.avatar}}" alt="">
                {%else %}
                    <ion-icon name="menu-outline"></ion-icon>
                {% endif %}
                <ion-icon name="caret-down-outline"></ion-icon>
            </a>
        </div>
    </div>
    <div id="navlinksContainer">
        <div id="navLinks">
            {% if user.is_authenticated %}
                <a href="{% url 'profile_page' user.username %}"><div><ion-icon name="person-circle-outline"> </ion-icon><span>{% if user.first_name %}{{ user.first_name | title }}{% else %}{{user.username}}{% endif %}</span></div></a>
                <a href="{% url 'edit_profile' user.username %}"><div><ion-icon name="settings-outline"></ion-icon> <span>Settings</span></div></a>
                <a href="{% url 'logout' %}"><div><ion-icon name="log-out-outline"></ion-icon> <span>Sign Out</span></div></a>
            {% else %}
                <a href="{% url 'signup' %}"><div><span>Sign Up</span></div></a>
                <a href="{% url 'login' %}"><div><span>Log In</span></div></a>
            {% endif %}
            <a onclick="SwitchTheme()"><div><ion-icon name="contrast-outline"></ion-icon> <span>Switch Theme</span></div></a>
        </div>
    </div>
</nav>

<div id="injectedContainer">
    {% block messages %}
        <ul class="messages" id="messages-list">
        {% if messages %}
            {% for message in messages %}
            <li>
                {% if message.tags %}
                     <div class="alert alert-{{ message.tags }} msg fade show" role="alert">{{ message }}</div>
                {% else %}
                    <div class="alert alert-info msg fade show" role="alert">{{ message }}</div>
                {% endif %}
            </li>
            {% endfor %}
        {% endif %}
        </ul>
    {% endblock %}
    {% block content %}
        <!-- Content Goes here -->
    {% endblock content %}
</div>

</body>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script src="{% static 'js/prism.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>
	window.addEventListener('message', function(e) {
		let message = e.data;
        if (message.iframeID && message.height) {
            let ifr = document.querySelector(`iframe#${message.iframeID}`);
            if (ifr) ifr.style.height = message.height + 'px';
        }
	} , false);
</script>
<script src="{% static 'js/requests.js' %}"></script>
{% block scripts %}
{% endblock %}
</html>

templates/edit_post.html
{% extends 'base.html' %}
{% load static %}
{% load template_tags %}

{% block title %}Edit Post{% endblock %}
{% block content %}
<div id="articleContainer" class="center">
    <br>
    <div class="articlebody">
        <form id="post_form" method="post" {% if newPost %} action="{% url 'create_post' %}" {% endif %}>
            {% csrf_token %}
            <div id="postInfo">
                {{form.status}}
                <span><label for="id_tags">Tags </label>{{form.taglist}}</span>
                <button class="flat mini" type="button" onclick="featured_image_handler(this)">Select Featured Image</button>
            </div>
            <div id="featured_image_selector">
                <span>Newly added images will be selectable after the post is saved.</span>
                <div id="images">

                </div>
            </div>
            <br>
            {{form.title}}
            {{form.excerpt}}
            <hr>
            {{form.content}}
            {{ form.featured_image.as_hidden }}
            <hr>
            {% if form.errors %}
                {{form.errors}}
            {% endif %}

            <div>
                <button type="submit">{% if newPost %} Create {% else %} Update {% endif %}</button>
                <button type="button" onclick="window.history.go(-1); return false;">Cancel</button>
            </div>
            <br>
        </form>
    </div>

</div>

{% endblock %}

{% block styles %}
    {{ form.media }}
    <link rel="stylesheet" href="{% static 'css/edit_post.css' %}">
    <link rel="stylesheet" href="{% static 'css/post_detail.css' %}">
{% endblock %}

{% block scripts %}
    <script>
        let editor = frames['id_content_ifr'];
        if (!editor) {
            setTimeout(() => {
                editor = frames['id_content_ifr'].contentDocument.body;
                applyTheme(editor)
            }, 2000)
        } else {
            applyTheme(editor.contentDocument.body)
        }
    </script>
    <script src={% static "js/featured_image.js" %}></script>
{% endblock %}

{% block meta %}

    {% if newPost %}
        {% meta_tags title="Write a Post" description="Create a new post" %}
    {% else %}
        {% meta_tags title=form.title.value|title description=form.excerpt.value %}
    {% endif %}

{% endblock meta %}

templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load template_tags %}
{% block styles %}
    {{ form.media }}
<link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">
{% endblock %}

{% block title %}Edit Profile{% endblock %}
{% block content %}
<div class="center edit_profile">
    <br>
    <div class="form-group">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <div id="mediaContainer">
                    <div>
                        <div id="banner_container">
                            <img id="banner" src="{{ aws_media_url }}{{ profileForm.banner.value }}" alt="Banner of {{userForm.username.value}}">
                            <label id="banner_lbl" for="id_banner">Change Banner</label> {{profileForm.banner}}
                        </div>
                        <div id="avatar_container">
                            <img id="avatar" src="{{ aws_media_url }}{{ profileForm.avatar.value }}" alt="Avatar of {{userForm.username.value}}">
                            <label for="id_avatar">Change Avatar</label> {{profileForm.avatar}}
                        </div>
                    </div>
                </div>
                <hr>
            <br>
            {{profileForm.banner}}
            <div id="userDataContainer">
                <label for="id_username">Username</label> {{userForm.username}}<br>
                <label for="id_first_name">First Name </label> {{userForm.first_name}}<br>
                <label for="id_last_name">Last Name </label>{{userForm.last_name}}<br>
                <label for="id_email">Email</label>{{userForm.email}}<br>
                <label for="id_bio">Bio</label>{{profileForm.bio}}<br>
                <span>URLs / Links</span>
                <div id="urls">
                    <span class="hint-input">
                        <label for="id_github">Github.com/</label>
                        {{profileForm.github}}
                    </span>
                    <span class="hint-input">
                        <label for="id_linkedin">LinkedIn.com/in/</label>
                        {{profileForm.linkedin}}
                    </span>
                    <span>
                        <label for="id_website">Website</label>
                        {{profileForm.website}}
                    </span>
                </div>
                <hr style="width: 100%">
            </div>
            <br>
            {{userForm.errors}}
            {{profileForm.errors}}
            <div><button type="submit">Update</button>
            <button type="button" onclick="window.history.go(-1); return false;">Cancel</button></div>
        </form>
    </div>

</div>

{% endblock %}

{% block meta %}
    {% meta_tags title="Editing @"|add:userForm.username|add:"'s Profile" description="Check out "|add:userForm.username|add:"'s profile on Easy Blog" %}
{% endblock meta %}

templates/elasticsearch.html
{% extends "base.html" %}
{% load template_tags %}
{% block content %}

{{ paginator.count }}
    {% for r in results %}
        {{ r.title }}
    {% endfor %}
{% endblock %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}

templates/followers.html
{% extends "base.html" %}
{% load static %}
{% load template_tags %}
{% block content %}
    <div class="center">
        <div id="header" onclick="location='{% url 'profile_page' target_user.username %}'">
            <ion-icon name="arrow-back-outline"></ion-icon>
            <div>
                {% if target_user.first_name %}
                    <span>{{ target_user.first_name | title }} {{ target_user.last_name | title }}</span><br>{% endif %}
                <span><small style="color: var(--text-color-dim); font-weight: 100">@{{ target_user.username }}</small></span>
            </div>
        </div>
        <div id="filter_controls">
            <button class="flat active">Followers</button>
            <button class="flat" onclick="location.href=`{% url 'following' target_user.username %}`">Following</button>
        </div>
        {% if users.has_other_pages %}
            <div class="pagination">
                {% if users.has_previous %}
                    <a href="?p={{ users.previous_page_number }}">
                        <ion-icon name="play-skip-back-outline"></ion-icon>
                    </a>
                {% else %}
                    <div class="disabled"><span><ion-icon name="play-skip-back-outline"></ion-icon></span></div>
                {% endif %}
                {% for i in users.paginator.page_range %}
                    {% if users.number == i %}
                        <div class="active"><span>{{ i }} <span class="sr-only"></span></span></div>
                    {% else %}
                        <a href="?p={{ i }}">
                            <div>{{ i }}</div>
                        </a>
                    {% endif %}
                {% endfor %}
                {% if users.has_next %}
                    <a href="?p={{ users.next_page_number }}">
                        <div>
                            <ion-icon name="play-skip-forward-outline"></ion-icon>
                        </div>
                    </a>
                {% else %}
                    <div class="disabled"><span><ion-icon name="play-skip-forward-outline"></ion-icon></span></div>
                {% endif %}
            </div>
        {% endif %}
        <div id="userlist-container">
            {% for u in users %}
                {% profile_card request u True %}
            {% empty%}
                <h3 style="font-weight: 100"><a href="{% url 'profile_page' target_user.username %}">@{{ target_user.username }}</a> does not have any followers at the moment.</h3>
            {% endfor %}
        </div>
        {% if users.has_other_pages %}
            <div class="pagination">
                {% if users.has_previous %}
                    <a href="?p={{ users.previous_page_number }}">
                        <ion-icon name="play-skip-back-outline"></ion-icon>
                    </a>
                {% else %}
                    <div class="disabled"><span><ion-icon name="play-skip-back-outline"></ion-icon></span></div>
                {% endif %}
                {% for i in users.paginator.page_range %}
                    {% if users.number == i %}
                        <div class="active"><span>{{ i }} <span class="sr-only"></span></span></div>
                    {% else %}
                        <a href="?p={{ i }}">
                            <div>{{ i }}</div>
                        </a>
                    {% endif %}
                {% endfor %}
                {% if users.has_next %}
                    <a href="?p={{ users.next_page_number }}">
                        <div>
                            <ion-icon name="play-skip-forward-outline"></ion-icon>
                        </div>
                    </a>
                {% else %}
                    <div class="disabled"><span><ion-icon name="play-skip-forward-outline"></ion-icon></span></div>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/profile-card.css' %}">
{% endblock %}

{% block meta %}
    {% meta_tags title=target_user.username|add:"'s Followers"|title description="View followers of @"|add:target_user.username|add:" on Easy Blog"%}
{% endblock meta %}

templates/index.html
{% extends "base.html" %} 
{% block content %}
<div class="center">
    <h1>Explore</h1>
    {% block homepage %}

    {% endblock %}
</div>
{%endblock%}

templates/report.html
{% extends "base.html" %}
{% load template_tags %}
{% block content %}
<form method="post" class="center" style="display: flex; flex-direction: column;" >
    <br>
    {% csrf_token %}
    <label for="id_reason">Reason</label>
    {{form.reason}}
    <br>
    <label for="id_comment">Comment</label>
    {{form.comment}}<br>
    <hr>
    <input type="submit" value="Report">
</form>
{% endblock %}

{% block meta %}
    {% meta_tags title="Submit a Report" %}
{% endblock meta %}